import React from "react"
import Layout from "../components/layout"
import SEO from "../components/seo"
import { BlogTitle, Paragraph } from "../components/atoms"

const GoogleHashCode = _ => {
  return (
    <Layout activePage="googlehashcode">
      <SEO title="Google Hash Code" /> 
      <BlogTitle>Hackaton: Google Hash Code</BlogTitle>
      <Paragraph>
      Deze hackaton behoort tot het domein innovatie, maar het kan eigenlijk ook onder persoonlijke ontwikkeling gerekend worden. Ik heb gekozen om deel te nemen aan de voorronde ‘Google Hash Code’ programmeerwedstrijd. In deze wedstrijd nemen teams over de hele wereld het tegen mekaar op in het oplossen van een programmatisch probleem. Aan de hand van een online puntensysteem werd er een scorebord bijgehouden. Ik vormde een team samen met drie vrienden/junior-collega’s van op Hogeschool PXL. Omwille van Covid-19 werd deze hackaton online georganiseerd, we konden dus jammer genoeg niet fysiek samen komen met het team.
      <br/><br/><img src={require("../assets/images/italent/googlehashcode/google-hash-code.png")}/>
      <br/>Als team hebben we besloten om wat voorbereidend werk te doen, zodat we op de dag van de waarheid niet voor verassingen kwamen te staan. Zo kwamen we enkele dagen voor de wedstrijd online samen om de voorbeeldoefening op te lossen. In deze oefening moesten we op een zo efficiënt mogelijke manier proberen ingrediënten op pizza’s te verdelen. Aan de hand van hoe optimaal de ingrediënten verdeeld werden, verdiende we punten. 
      <br/><br/><img src={require("../assets/images/italent/googlehashcode/ghc-pizza.png")}/>
      <br/>Tijdens deze oefensessie hebben we besloten met welke technologie we samen zouden werken tijdens de wedstrijd. Aangezien we niet fysiek samenzaten, was het niet evident om aan hetzelfde project te werken. We probeerden eerst de nieuwe plugin ‘Code With Me’ van Jetbrains, waarmee we samen konden werken aan hetzelfde Java-project in IntelliJ. Jammer genoeg bleek deze tool nog iets te primitief om betrouwbaar te kunnen gebruiken. Uiteindelijk hebben we beslist om de opdracht uit te voeren in programmeertaal C#, met een plugin van Visual Studio. Toen onze proefoplossing eindelijk af was, is er iets misgegaan met de code sharing tool van Visual Studio, waardoor we data verloren zijn geraakt. Een wijze les, we prijsden ons gelukkig dat we de oefensessie hadden gedaan en dit probleem dus niet voorhadden tijdens de effectieve wedstrijd.
      <br/><br/>Tijdens de dag van de wedstrijd werd de opdracht ingeleid door een livestream die we samen met het team hebben gevolgd. Om de communicatie vlot te laten verlopen en om de studenten toch het gevoel te geven dat we effectief allemaal samenkwamen, werd er een soort online hub opgezet door IT-bedrijf Info Support. Dit was voor mij een nieuwe ervaring die ik wel zeer leuk vond om te gebruiken, het leek een beetje op een soort spelletje. Wanneer je even wou vragen hoe het binnen een ander team eraan toe ging, moest je gewoon naar een ander tafeltje lopen en kon je met hen praten.
      <br/><br/><img src={require("../assets/images/italent/googlehashcode/ghc-hub.png")}/>
      <br/>Het doel van de opdracht bestond erin om een algoritme te bouwen dat verkeerslichten in een virtuele stad bestuurde, we moesten zo snel en zoveel mogelijk virtuele auto’s op hun bestemming laten arriveren.
      <br/><br/><img src={require("../assets/images/italent/googlehashcode/ghc-roads-1.png")}/>
        <img class="center-image" src={require("../assets/images/italent/googlehashcode/ghc-roads-2.png")}/>
      <br/>De opdracht was in het begin niet helemaal duidelijk, onze taak bestond enkel uit het maken van een file waarin stond hoe de lichten zich zouden gaan gedragen. Google zelf zou dan onze score berekenen aan de hand van hun simulator. Echter hebben we in het begin veel tijd verloren omdat we dachten dat we zelf ook de simulatie moesten nabouwen. We splitsten het werk op in twee teams van twee personen, ik ging aan de slag met het bouwen van de modellen en het berekenen van de meest optimale lichtstanden. Het andere team van twee zou ervoor zorgen dat het invoerbestand uitgelezen werd en omgezet werd naar onze modellen.
      <br/><br/>Jammer genoeg zaten we op het einde van de opdracht met een probleem dat te maken had met performantie van het inleessysteem, waardoor het inladen van de grotere inputbestanden enorm lang duurde. Dit heeft als gevolg gehad dat we niet alle input data binnen de tijd door ons algoritme hebben kunnen gooien, en hierdoor dus veel punten zijn misgelopen. Bij de bestanden waarin het wel gelukt was scoorde we bijzonder hoge scores, 99 tot 100% van de auto’s kwam binnen de tijd op hun bestemming aan. Het leverde ons op het einde van de rit een totaal van 5.7 miljoen punten op.
      <br/><br/><img src={require("../assets/images/italent/googlehashcode/ghc-score.png")}/>
      <br/>Ik bleef na de wedstrijd in eerste instantie toch achter met een redelijk zuur gevoel, omdat ik wist dat ons algoritme nog veel meer punten had kunnen scoren als we alle data erdoor hadden kunnen gooien. Even later heb ik dit echter toch kunnen relativeren. Ik besefte dat dit soort zaken er natuurlijk bij horen wanneer je voor de eerste keer aan een dergelijke wedstrijd mee doet, zeker in team. Het feit dat we als team niet fysiek samenzaten, maakte de samenwerking zeker niet gemakkelijk. Maar gezien onze goede voorbereiding en leuke sfeer binnen het team hebben we er toch een leuke avond van gemaakt. En hoe je het ook draait of keert, dit is uiteraard het belangrijkste aspect van een dergelijke hackaton. Ik heb ook wel ervaren dat de online samenwerkingstools, om echt samen in real-time aan hetzelfde project te werken, nog niet helemaal op punt staat. Ik hoop dat dit wanneer ik deelneem aan een volgende wedstrijd/hackaton wel beter op punt zal staan. Of natuurlijk dat we als team wel gewoon fysiek samen kunnen komen, zoals het hoort bij een hackaton. 
      <br/><br/>Ik heb tijdens de Google Hash Code ook ontdekt dat het competitieve element ervan met live scoreborden echt wel een hele leuke trigger is om tijdens het coderen net dat tikkeltje meer van jezelf te geven samen met je team. Het gaf een zalig gevoel wanneer de punten in de miljoenen binnenstroomde, zeker wanneer we dit achteraf konden bespreken en vergelijken met de andere teams. Ook al was het in een virtuele hub. Al bij al was de hackaton een zéér leuke ervaring en zou ik zonder twijfel opnieuw meedoen.
      </Paragraph>
    </Layout>
  )
}

export default GoogleHashCode
